site_name: Fundamentos de Informática
site_description: Apuntes y material de clase
use_directory_urls: false

# Información Institucional (Pie de página y Redes)
copyright: Departamento de Ingeniería de Sistemas y Automática. EII. Universidad de Valladolid

# Iconos sociales (Aparecen en el pie de página)
extra:
  social:
    - icon: fontawesome/solid/university
      link: https://www.uva.es
      name: Universidad de Valladolid
    - icon: fontawesome/solid/building
      link: http://www.isa.uva.es
      name: Departamento ISA

theme:
  name: material
  logo: img/logo_eii.jpg # Ruta al archivo del logotipo (debes subirlo a docs/img/)
  favicon: img/logo_eii.jpg # Icono de la pestaña del navegador
  language: es  # Para que los botones y búsqueda estén en español
  palette:
    primary: indigo # Puedes cambiarlo a 'teal', 'blue', etc.
    accent: indigo
  features:
    - navigation.tabs # Menú horizontal arriba
    - navigation.sections # Organización por secciones
    - toc.integrate # Integra el índice en la barra lateral izquierda
    - search.suggest
    - content.code.copy # Botón para copiar código

markdown_extensions:
  - pymdownx.arithmatex: # PARA MATEMÁTICAS (LaTeX)
      generic: true
  - pymdownx.betterem
  - pymdownx.details # Para bloques colapsables
  - pymdownx.superfences # Para código y diagramas
  - tables # Para tablas académicas
  - md_in_html
  - admonition # Para cuadros de "Nota", "Aviso", "Ejemplo"
  - attr_list # Para atributos en imágenes y otros elementos
  - pymdownx.snippets: # Para incluir ficheros comunes
      base_path: docs
  - toc:
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode

nav:
  - Inicio: index.md
  - Lenguajes de Programación: Lenguajes_de_programacion.md
  - Representación de la Información: Representacion_de_la_informacion.md
  - Arquitectura de Computadores: Arquitectura_de_computadores.md

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/print_button.js # Script para botón de imprimir
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css  # Ajusta la ruta si tu archivo se llama distinto

plugins:
  - search
  - print-site:
      add_to_navigation: true